### ISSUE TITLE
libc10.dylib cannot be found

### ISSUE THREAD

**Issue by pikseliahky** [elgiano/nn.ar#1]
Hi, 
I tried to download and install the arm64 release but I'm getting following errors:

*** ERROR: dlopen '/Users/XXXX/Library/Application Support/SuperCollider/Extensions/RAVE/RAVE_scsynth.scx' err 'dlopen(/Users/XXXX/Library/Application Support/SuperCollider/Extensions/RAVE/RAVE_scsynth.scx, 0x0002): Library not loaded: @rpath/libc10.dylib
  Referenced from: <F1B6A8DE-E467-376E-8F6A-4648D0BCB092> /Users/XXXX/Library/Application Support/SuperCollider/Extensions/RAVE/RAVE_scsynth.scx
  Reason: tried: '/Users/XXXX/Library/Application Support/SuperCollider/Extensions/RAVE/ignore/libc10.dylib' (no such file), '/Users/XXXX/Library/Application Support/SuperCollider/Extensions/RAVE/ignore/libc10.dylib' (no such file), '/usr/lib/libc10.dylib' (no such file, not in dyld cache)'

Not sure what could be causing this? The dylib file is located in the /ignore folder but cannot be found for some reason.
My system is M2, OS 13.4.

**Comment by elgiano** [comment]
Hello! I'm sorry I haven't tested it on mac myself, so here we go :)
Did you download the 0.0.2-alpha version from releases? Or did you build it yourself? For me the first strange thing is that your extensions is called RAVE and not nn.ar... and the scx should be called NNUGens.scx

**Comment by pikseliahky** [comment]
Oops, I am sorry, I tried a different UGen, please ignore the first issue. The one with NN.load is that I'm getting an error "ERROR: NNModelInfo: can't load info file '/Users/XXXX/Library/Application Support/SuperCollider/tmp/nn-sc-1020.yaml'" when trying to run the help example. This is the downloaded alpha release, I tried to run:

`NN.load(\model, "/Users/XXXX/Documents/rave-models/percussion.ts")`

**Comment by elgiano** [comment]
No problem :) There was actually an error in the mac build that I fixed thanks to your issue, so thanks!

About NN.load, can you share the post window messages (before the error) as well?

**Comment by pikseliahky** [comment]
Great, I will try the new build, thank you. The messages are as follows:

```
-> NNModel(nil, nil)
FAILURE IN SERVER /cmd failed
ERROR: NNModelInfo: can't load info file '/Users/apple/Library/Application Support/SuperCollider/tmp/nn-sc-1038.yaml'
```


But there seems to be also a problem with the library:

```
*** ERROR: dlopen '/Users/XXXX/Library/Application Support/SuperCollider/Extensions/nn.ar/NNUGens_scsynth.scx' err 'dlopen(/Users/apple/Library/Application Support/SuperCollider/Extensions/nn.ar/NNUGens_scsynth.scx, 0x0002): Library not loaded: @rpath/libc10.dylib
  Referenced from: <8151BD5E-00C2-3889-BA07-375FE929643B> /Users/apple/Library/Application Support/SuperCollider/Extensions/nn.ar/NNUGens_scsynth.scx
  Reason: tried: '/Users/XXXX/Library/Application Support/SuperCollider/Extensions/nn.ar/ignore/libc10.dylib' (code signature in <35E8B366-A309-3BCE-BB34-FF2B9ECB9160> '/Users/apple/Library/Application Support/SuperCollider/Extensions/nn.ar/ignore/libc10.dylib' not valid for use in process: library load disallowed by system policy), '/Users/XXXX/Library/Application Support/SuperCollider/Extensions/nn.ar/ignore/libc10.dylib' (code signature in <35E8B366-A309-3BCE-BB34-FF2B9ECB9160> '/Users/apple/Library/Application Support/SuperCollider/Extensions/nn.ar/ignore/libc10.dylib' not valid for use in process: library load disallowed by system policy), '/usr/lib/libc10.dylib' (no such file, not in dyld cache)'
```

When I try NN.load, I am getting the error messages above + a pop-up window saying "“libc10.dylib” is damaged and can’t be opened. You should move it to the Bin."

**Comment by elgiano** [comment]
Try this in supercollider:
```supercollider
format("xattr -d -r com.apple.quarantine %", (Platform.userExtensionDir +/+ "nn.ar").quote).runInTerminal;
format("xattr -d -r com.apple.quarantine %", (Platform.userExtensionDir +/+ "nn.ar/ignore").quote).runInTerminal;
```

Then restart scsynth and try again

**Comment by pikseliahky** [comment]
Thanks, that did the trick!

**Comment by elgiano** [comment]
Thank you! It helped solving these mac issues <3
