### ISSUE TITLE
Issue with runnin nn

### ISSUE THREAD

**Issue by Adampultz** [elgiano/nn.ar#3]
Hi Gianluca,

thanks so much for doing this work.

I am on Apple M1Max with OS 13.3.1 

I have downloaded and installed the prebuilt release, but when I try to run the first part of your template patch, I get the following error message: "“libc10.dylib” is damaged and can’t be opened. You should move it to the Bin."

When I press cancel, the sc window reads:

"^^ The preceding error dump is for ERROR: NNModelInfo: can't load info file '/Users/adammac2023/Library/Application Support/SuperCollider/tmp/nn-sc-1007.yaml'"

I have tried building from source but have had to face that I am not skilled enough to make that work either.

Best, Adam

**Comment by elgiano** [comment]
Maestro,

I'm not very familiar with mac, but just to rule out one thing, have you ran this:
```sclang
runInTerminal("xattr -d -r com.apple.quarantine %".format(Platform.userExtensionDir +/+ "nn.ar"))
```

and this shouldn't be necessary, but just to be sure again:
```sclang
runInTerminal("xattr -d -r com.apple.quarantine %".format(Platform.userExtensionDir +/+ "nn.ar/ignore"))
```

and are we sure you got the mac arm release?

**Comment by Adampultz** [comment]
This was my bad, sorry. I hadn't been attentive to an error message I got when running those terminal scripts. On my computer, SuperCollider/Extensions is in a folder called /Application Support/ so I had to copy the enitre path into the SuperCollider code (to make terminal ignore the space) and enclose it in single quotes, like this:

```
runInTerminal("xattr -d -r com.apple.quarantine %".format("'/Users/adammac2023/Library/Application Support/SuperCollider/Extensions/nn.ar'"))
```

**Comment by elgiano** [comment]
Greaaat! So does it work now? I'll update the readme with the quotes

```supercollider
runInTerminal("xattr -d -r com.apple.quarantine" + shellQuote(Platform.userExtensionDir +/+ "nn.ar"))
```

**Comment by Adampultz** [comment]
Yes, I am getting sound but also what appears to be dropouts. It’s entirely possible it’s my fault, I am a total noob with this stuff. Will do more testing and report back.

Adam Pultz Melbye
web <https://adampultz.com/> | bandcamp <https://adampultz.bandcamp.com/> | vimeo <https://vimeo.com/adampultz>

**Comment by elgiano** [comment]
Maybe this got better with v.0.0.3-alpha? Anyway, I suggest we continue the discussion on scsynth.org:

https://scsynth.org/t/experiences-with-rave-ugen/6398/25

And the README now should have correct informations for mac quarantine stuff, also including the error you got.
Thanks for opening the issue <3
