### ISSUE TITLE
NNModelInfo: can't load info file error again

### ISSUE THREAD

**Issue by pikseliahky** [elgiano/nn.ar#4]
When running the NNModel.load() I am again getting the error (M2, Ventura):

```
-> NNModel(nil, nil)
FAILURE IN SERVER /cmd failed
ERROR: NNModelInfo: can't load info file '/Users/XXXXLibrary/Application Support/SuperCollider/tmp/nn-sc-1017.yaml'
```

I did unquarantine both the nn.ar and the ignore folder according the instructions. Not sure what can be wrong?

**Comment by elgiano** [comment]
Any error when you booted the server?

it looks like the PluginCmd was not registered, which I guess it means that the plugin was not loaded

**Comment by pikseliahky** [comment]
You are right - I had to delete any other copies of the libraries (such as libtorch_cpu.dylib) in the SuperCollider path (such as the one in the original RAVE directory), otherwise NN would not load. Now it is working again, thanks!

**Comment by elgiano** [comment]
No problem, thank you!
